import React from 'react';
import Footer from '../../components/Footer';

export default function Privacy() {
    return (
        <div>
            <div>
                <section className='section text-center'>
                    <div>
                        <h1 data-aos='fade-up'
                            data-aos-duration='1000'
                            className='font-serif font-bold text-7x1 '>
                        </h1>

                        {/*Terms and Privacy content */}
                        <div>
                            <h1 className='headings1'>SECONDS TECH LIMITED (“the Company”)</h1>
                            <h1 className='headings1'>GENERAL TERMS AND CONDITIONS</h1>
                            <h2 className='headings'>1. Introduction and Agreement to terms</h2>
                            <p className='texts'>Seconds Tech Limited (“the Company”), a private limited liability company established in Uganda, having its offices at P. O. Box 74940 Clock-Tower, Kampala. The Company is an E-hailing company that is remodeling the concept of luxury transportation, advancing past technological barriers and integrating a network of systems to provide users with unique solutions to their chosen means of transport. The Company operates an online transportation platform under the brand “SECONDS” majoring in luxury ride hailing, package delivery, partial freight, ambulance contacting, car maintenance and electric bikes in Uganda, Egypt and Tanzania (“territories”)</p>
                            <p className='texts'>These Terms and Conditions (“Terms”) govern the access or use by you, an individual, from within any country in the world of applications, websites, content, products, and services (the “Services”) made available by the Company. </p>
                            <h2 className='headings'>PLEASE READ THESE TERMS CAREFULLY BEFORE ACCESSING OR USING THE SERVICES.</h2>
                            <p className='texts'>Your access and use of the Services constitute your agreement to be bound by these Terms, which establishes a contractual relationship between you and the Company. If you do not agree to these Terms, you may not access or use the Services. These Terms expressly supersede prior agreements or arrangements with you. The Company may immediately terminate these Terms or any Services with respect to you, or generally cease offering or deny access to the Services or any portion thereof, at any time for any reason.</p>
                            <p className='texts'>Supplemental terms may apply to certain Services, such as policies for a particular feature, event, activity or promotion, and such supplemental terms will be disclosed to you in connection with the applicable Services. Supplemental terms are in addition to, and shall be deemed a part of, the Terms for the purposes of the applicable Services. Supplemental terms shall prevail over these Terms in the event of a conflict with respect to the applicable Services.</p>
                            <p className='texts'>The Company may amend the Terms related to the Services from time to time. Amendments will be effective upon the Company’s posting of such updated Terms at this location or the amended policies or supplemental terms on the applicable Service. Your continued access or use of the Services after such posting constitutes your consent to be bound by the Terms, as amended.</p>
                            <p className='texts'>The Company shall take all steps as far as is reasonably practicable to alert you about any changes by updating the “Last updated” date of these Terms of Use. You agree to waive any right whether arising from these terms or elsewhere, to receive specific notice of each such change.</p>
                            <p className='texts'>Our collection and use of personal information in connection with the Services is as provided in the Company’s Privacy Policy located at _________________________ . the Company may provide to a claims processor or an insurer any necessary information (including your contact information) if there is a complaint, dispute or conflict, which may include an accident, involving you and a Third Party Provider (including a transportation network company driver) and such information or data is necessary to resolve the complaint, dispute or conflict.</p>
                            <h1 className='headings'>2. The Services</h1>
                            <p className='texts'>The Services constitute a technology platform that enables users of the Company’s mobile application (“the Application”) to arrange and schedule transportation and/or logistics services with company contracted employees or independent third party providers of such services, including independent third party transportation providers and independent third party logistics providers under agreement with the Company or certain of Company’s affiliates (“Third Party Providers”). Unless otherwise agreed by the Company in a separate written agreement with you, the Services are made available solely for your personal, non-commercial use. You acknowledge that the Company through the Application offers numerous features such as luxury ride hailing, package delivery, partial freight, ambulance contacting, car maintenance and electric bikes. THAT SAVE FOR THE LUXURY RIDE HAILING AND PACKAGE DELIVERY WHERE THE OPERATORS ARE FULLY CONTRACTED EMPLOYEES OF THE COMPANY, YOU ACKNOWLEDGE THAT THE OTHER FEATURES SUCH AS AMBULANCE CONTACTING, CAR MAINTENANCE, PARTIAL FREIGHT AND ELECTRIC BIKES ARE NOT PROVIDED BY THE COMPANY AS A TRANSPORTATION CARRIER BUT ARE PROVIDED BY INDEPENDENT THIRD PARTY CONTRACTORS WHO ARE NOT EMPLOYED BY SECONDS TECH OR ANY OF ITS AFFILIATES.</p>
                            <h2 className='headings'>License.</h2>
                            <p className='texts'>Subject to your compliance with these Terms, the Company grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferrable license to: </p>
                            <ul className='textsList'>
                                <li> 1. access and use the Applications on your personal device solely in connection with your use of the Services; and </li>
                                <li> 2. access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, non-commercial use. </li>
                            </ul>
                            <p className='texts'>Any rights not expressly granted herein are reserved by the Company and the Company’s licensors.</p>
                            <h2 className='headings'>Restrictions.</h2>
                            <p className='texts'>You may not: remove any copyright, trademark or other proprietary notices from any portion of the Services; reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by the Company; decompile, reverse engineer or disassemble the Services except as may be permitted by applicable law; link to, mirror or frame any portion of the Services; cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Services or unduly burdening or hindering the operation and/or functionality of any aspect of the Services; or attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.</p>
                            <h2 className='headings'>Provision of the Services.</h2>
                            <p className='texts'>You acknowledge that portions of the Services may be made available under the Company’s various brands or request options associated with transportation or logistics, including the transportation request brands currently referred to SECONDS. You also acknowledge that the Services may be made available under such brands or request options by or in connection with: certain of the Company’s subsidiaries and affiliates; or independent Third Party Providers, including transportation network company drivers, transportation charter permit holders or holders of similar transportation permits, authorizations or licenses.</p>
                            <h2 className='headings'>Third Party Services and Content.</h2>
                            <p className='texts'>The Services may be made available or accessed in connection with third party services and content (including advertising) that the Company does not control. You acknowledge that different terms of use and privacy policies may apply to your use of such third-party services and content. The Company does not endorse such third-party services and content and in no event shall the Company be responsible or liable for any products or services of such third-party providers. </p>
                            <p className='texts'>These third-party beneficiaries are not parties to this contract and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third-party beneficiary’s terms of service.</p>
                            <h2 className='headings'>Ownership.</h2>
                            <p className='texts'>The Services and all rights therein are and shall remain the Company’s property or the property of the Company’s licensors. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner the Company’s company names, logos, product and service names, trademarks or services marks or those of the Company’s licensors.</p>
                            <h2 className='headings'>3. Your Use of the Services</h2>
                            <h3 className='headings'>User Accounts</h3>
                            <p className='texts'>In order to use most aspects of the Services, you must register for and maintain an active personal user Services account (“Account”). You must be at least 18 years of age, or the age of legal majority in your jurisdiction (if different than 18), to obtain an Account. Account registration requires you to submit to the Company certain personal information, such as your name, address, mobile phone number and age, as well as at least one valid payment method (either a credit card or accepted payment partner). You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, may result in your inability to access and use the Services or the Company’s termination of these Terms with you. You are responsible for all activity that occurs under your Account, and you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by the Company in writing, you may only possess one Account.</p>
                            <h3 className='headings'>User Requirements and Conduct.</h3>
                            <p className='texts'>The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to receive transportation or logistics services from Third Party Providers unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when using the Services, and you may only use the Services for lawful purposes (e.g., no transport of unlawful or hazardous materials). You will not, in your use of the Services, cause nuisance, annoyance, inconvenience, or property damage, whether to the Third-Party Provider or any other party. In certain instances, you may be asked to provide proof of identity to access or use the Services, and you agree that you may be denied access to or use of the Services if you refuse to provide proof of identity.</p>
                            <h3 className='headings'>Text Messaging.</h3>
                            <p className='texts'>By creating an Account, you agree that the Services may send you text (SMS) messages as part of the normal business operation of your use of the Services. You may opt-out of receiving text (SMS) messages from the Company.</p>
                            <h3 className='headings'>Promotional Codes</h3>
                            <p className='texts'>The Company may, in its sole discretion, create promotional codes that may be redeemed for Account credit, or other features or benefits related to the Services and/or a Third Party Provider’s services, subject to any additional terms that the Company establishes on a per promotional code basis (“Promo Codes”). You agree that Promo Codes: (i) must be used for the intended audience and purpose, and in a lawful manner; (ii) may not be duplicated, sold or transferred in any manner, or made available to the general public (whether posted to a public form or otherwise), unless expressly permitted by the Company; (iii) may be disabled by the Company at any time for any reason without liability to the Company; (iv) may only be used pursuant to the specific terms that the Company establishes for such Promo Code; (v) are not valid for cash; and (vi) may expire prior to your use. The Company reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that the Company determines or believes that the use or redemption of the Promo Code was in error, fraudulent, illegal, or in violation of the applicable Promo Code terms or these Terms.</p>
                            <h3 className='headings'>User Provided Content.</h3>
                            <p className='texts'>The Company may, in it’s sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to the Company through the Services textual, audio, and/or visual content and information, including commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions (“User Content”). Any User Content provided by you remains your property. However, by providing User Content to the Company, you grant the Company a worldwide, perpetual, irrevocable, transferrable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats and distribution channels now known or hereafter devised (including in connection with the Services and the Company’s business and on third-party sites and services), without further notice to or consent from you, and without the requirement of payment to you or any other person or entity.</p>
                            <p className='texts'>You represent and warrant that: (i) you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and releases necessary to grant the Company the license to the User Content as set forth above; and (ii) neither the User Content nor your submission, uploading, publishing or otherwise making available of such User Content nor the Company’s use of the User Content as permitted herein will infringe, misappropriate or violate a third party’s intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
                            <p className='texts'>You agree to not provide User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by the Company in its sole discretion, whether or not such material may be protected by law. The Company may, but shall not be obligated to, review, monitor, or remove User Content, at the Company’s sole discretion and at any time and for any reason, without notice to you.</p>
                            <h3 className='headings'>Network Access and Devices.</h3>
                            <p className='texts'>You are responsible for obtaining the data network access necessary to use the Services. Your mobile network’s data and messaging rates and fees may apply if you access or use the Services from a wireless-enabled device and you shall be responsible for such rates and fees. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. The Company does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.</p>
                            <h2 className='headings'>4. Payment</h2>
                            <p className='texts'>You understand that use of the Services may result in charges to you for the services or goods you receive from a Third-Party Provider (“Charges”). After you have received services or goods obtained through your use of the Service, the Company will facilitate your payment of the applicable Charges on behalf of the Third Party Provider as such Third Party Provider’s limited payment collection agent. Payment of the Charges in such manner shall be considered the same as payment made directly by you to the Third-Party Provider. Charges may include other applicable fees, tolls, and/or surcharges including a booking fee, national and local council charges, airport surcharges and processing fees for split payments, and will be inclusive of applicable taxes where required by law. Charges paid by you are final and non-refundable, unless otherwise determined by the Company. You retain the right to request lower Charges from a Third-Party Provider for services or goods received by you from such Third-Party Provider at the time you receive such services or goods. The Company will respond accordingly to any request from a Third-Party Provider to modify the Charges for a particular service or good.</p>
                            <p className='texts'>All Charges are due immediately and payment will be facilitated by the Company using the preferred payment method designated in your Account, after which the Company will send you a receipt by email. If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that the Company may, as the Third-Party Provider’s limited payment collection agent, use a secondary payment method in your Account, if available.</p>
                            <p className='texts'>As between you and the Company, the Company reserves the right to establish, remove and/or revise Charges for any or all services or goods obtained through the use of the Services at any time in the Company’s sole discretion. Further, you acknowledge and agree that Charges applicable in certain geographical areas may increase substantially during times of high demand. The Company will use reasonable efforts to inform you of Charges that may apply, provided that you will be responsible for Charges incurred under your Account regardless of your awareness of such Charges or the amounts thereof. The Company may from time to time provide certain users with promotional offers and discounts that may result in different amounts charged for the same or similar services or goods obtained through the use of the Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you. You may elect to cancel your request for services or goods from a Third-Party Provider at any time prior to such Third-Party Provider’s arrival, in which case you may be charged a cancellation fee.</p>
                            <p className='texts'>This payment structure is intended to fully compensate the Third-Party Provider for the services or goods provided. Except with respect to taxicab transportation services requested through the Application, the Company does not designate any portion of your payment as a tip or gratuity to the Third-Party Provider. Any representation by the Company (on the Company’s website, in the Application, or in Company’s marketing materials) to the effect that tipping is “voluntary,” “not required,” and/or “included” in the payments you make for services or goods provided is not intended to suggest that the Company provides any additional amounts, beyond those described above, to the Third-Party Provider. You understand and agree that, while you are free to provide additional payment as a gratuity to any Third-Party Provider who provides you with services or goods obtained through the Service, you are under no obligation to do so. Gratuities are voluntary. After you have received services or goods obtained through the Service, you will have the opportunity to rate your experience and leave additional feedback about your Third-Party Provider.</p>
                            <h3 className='headings'>Repair or Cleaning Fees.</h3>
                            <p className='texts'>You shall be responsible for the cost of repair for damage to, or necessary cleaning of, Third Party Provider vehicles and property resulting from use of the Services under your Account in excess of normal “wear and tear” damages and necessary cleaning (“Repair or Cleaning”). In the event that a Third-Party Provider reports the need for Repair or Cleaning, and such Repair or Cleaning request is verified by the Company in the Company’s reasonable discretion, the Company reserves the right to facilitate payment for the reasonable cost of such Repair or Cleaning on behalf of the Third-Party Provider using your payment method designated in your Account. Such amounts will be transferred by the Company to the applicable Third-Party Provider and are non-refundable.</p>
                            <h2 className='headings'>5. Disclaimers; Limitation of Liability; Indemnity.</h2>
                            <h3 className='headings'>DISCLAIMER.</h3>
                            <p className='texts'>The services are provided “as is” and “as available.” The company disclaims all representations and warranties, express, implied or statutory, not expressly set out in these terms, including the implied warranties of merchantability, fitness for a particular purpose and non-infringement. In addition, the company makes no representation, warranty, or guarantee regarding the reliability, timeliness, quality, suitability or availability of the services or any services or goods requested through the use of the services, or that the services will be uninterrupted or error-free. The company does not guarantee the quality, suitability, safety or ability of third party providers. You agree that the entire risk arising out of your use of the services, and any service or good requested in connection therewith, remains solely with you, to the maximum extent permitted under applicable law.</p>
                            <h3 className='headings'>LIMITATION OF LIABILITY.</h3>
                            <p className='texts'>The company shall not be liable for indirect, incidental, special, exemplary, punitive or consequential damages, including lost profits, lost data, personal injury or property damage related to, in connection with, or otherwise resulting from any use of the services, even if the company has been advised of the possibility of such damages. The company shall not be liable for any damages, liability or losses arising out of: (i) your use of or reliance on the services or your inability to access or use the services; or (ii) any transaction or relationship between you and any third-party provider, even if the company has been advised of the possibility of such damages. The company shall not be liable for delay or failure in performance resulting from causes beyond the company’s reasonable control. You acknowledge that third party transportation providers providing transportation services requested through some request brands may offer ridesharing or peer-to-peer transportation services and may not be professionally licensed or permitted. In no event shall the company’s total liability to you in connection with the services for all damages, losses and causes of action exceed ___________________ (ascertain the sum)</p>
                            <p className='texts'>The company’s services may be used by you to request and schedule transportation, goods or logistics services with third party providers, but you agree that the company has no responsibility or liability to you related to any transportation, goods or logistics services provided to you by third party providers other than as expressly set forth in these terms.</p>
                            <p className='texts'>The limitations and disclaimer in this section do not purport to limit liability or alter your rights as a consumer that cannot be excluded under applicable law.</p>
                            <h3 className='headings'>INDEMNITY.</h3>
                            <p className='texts'>You agree to indemnify and hold the Company and its officers, directors, employees and agents harmless from any and all claims, demands, losses, liabilities, and expenses (including legal fees) arising out of or in connection with: (i) your use of the Services or services or goods obtained through your use of the Services; (ii) your breach or violation of any of these Terms; (iii) the Company’s use of your User Content; or (iv) your violation of the rights of any third party, including Third Party Providers.</p>
                            <h2 className='headings'>6. Lost Property</h2>
                            <p className='texts'>You understand and agree that it is your responsibility to ensure that you remove your property from the vehicle of the Company or a Third-Party Provider when disembarking. Should you leave your property in the vehicle of the Company or a Third-Party Provider, the Third-Party Provider may hand over your property to you, the Company or to the Company local service entity.</p>
                            <p className='texts'>Whilst you may expect Third Party Providers to hand over your property to you, the offices of the Company or the the Company local service entity, shall not be held liable in the event of the Third-Party Provider not handing over your property as expected. Moreover, the Company or the Company local service entity shall not be liable for the loss or damage to your property whilst it is in transit.</p>
                            <p className='texts'>Whilst the Company or the Company local service entity will take reasonable steps to establish the owner of property left in a Third Party Provider’s vehicle if returned to the offices of the Company or the Company local service entity, when your property is in the Company’s or the Company local service entity’s possession, you understand and agree that: (i) the Company or the Company local service entity will only keep your property in its possession for a maximum period of three months from the date on which the Third Party Provider handed your property to the Company or the Company local service entity; and (ii) should you fail to collect your property from the Company or the Company local service entity before the expiry of the three month period stipulated, the Company or the Company local service entity will be entitled to deal with your property as it deems fit and you shall have no claim whatsoever against the Company or the Company local service entity in respect of your unclaimed property.</p>
                            <h2 className='headings'>7. Governing Law; Arbitration.</h2>
                            <p className='texts'>Except as otherwise set forth in these Terms, these Terms shall be exclusively governed by and construed in accordance with the laws of Uganda, excluding its rules on conflicts of laws. The Vienna Convention on the International Sale of Goods of 1980 (CISG) shall not apply. Any dispute, conflict, claim or controversy arising out of or broadly in connection with or relating to the Services or these Terms, including those relating to its validity, its construction or its enforceability (any “Dispute”) shall be first mandatorily submitted to Arbitration under the Arbitration and Conciliation Act, Cap 4. </p>
                            <p className='texts'>If such Dispute has not been settled within sixty (60) days after a request for arbitration, such Dispute can be referred to and shall be exclusively and finally resolved by the High Court of Uganda. The existence and content of the arbitration and litigation proceedings, including documents and briefs submitted by the parties, correspondence from and to the Courts, shall remain strictly confidential and shall not be disclosed to any third party without the express written consent from the other party unless: (i) the disclosure to the third party is reasonably required in the context of conducting the dispute resolution proceedings; and (ii) the third party agrees unconditionally in writing to be bound by the confidentiality obligation stipulated herein.</p>
                            <h2 className='headings'>8. Other Provisions</h2>
                            <h3 className='headings'>Claims of Copyright Infringement.</h3>
                            <p className='texts'>Claims of copyright infringement should be sent to the Company’s designated agent.</p>
                            <h3 className='headings'>Notice.</h3>
                            <p className='texts'>The Company may give notice by means of a general notice on the Services, electronic mail to your email address in your Account, or by written communication sent to your address as set forth in your Account. You may give notice to the Company by written communication to the Company's address at P. O. BOX 74940 Clock-Tower, Kampala. (you can input email address as well)</p>
                            <h3 className='headings'>General.</h3>
                            <p className='texts'>You may not assign or transfer these Terms in whole or in part without the Company’s prior written approval. You give your approval to the Company for it to assign or transfer these Terms in whole or in part, including to: (i) a subsidiary or affiliate; (ii) an acquirer of the Company’s equity, business or assets; or (iii) a successor by merger. No joint venture, partnership, employment or agency relationship exists between you, the Company or any Third Party Provider as a result of the contract between you and the Company or use of the Services.</p>
                            <h3 className='headings'>Severability</h3>
                            <p className='texts'>If any provision of these Terms is held to be illegal, invalid or unenforceable, in whole or in part, under any law, such provision or part thereof shall to that extent be deemed not to form part of these Terms but the legality, validity and enforceability of the other provisions in these Terms shall not be affected. In that event, the parties shall replace the illegal, invalid or unenforceable provision or part thereof with a provision or part thereof that is legal, valid and enforceable and that has, to the greatest extent possible, a similar effect as the illegal, invalid or unenforceable provision or part thereof, given the contents and purpose of these Terms. These Terms constitute the entire agreement and understanding of the parties with respect to its subject matter and replaces and supersedes all prior or contemporaneous agreements or undertakings regarding such subject matter. </p>
                        </div>
                    </div>
                    <div>
                    </div>
                </section>
            </div>
            <Footer />
        </div>
    );
}